### ISSUE TITLE
is there an issue with object array selectors?

### ISSUE THREAD

**Issue by pljakobs** [mikee47/ConfigDB#63]
I've been trying to figure this out for a while, and more and more, I believe that something is amiss with the array update through json using selectors. 
I've build a simple test schema:
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "store":true,
  "properties": {
    "x":{
      "type":"array",
      "items": {
        "type":"object",
        "properties":{
          "name":{
            "type":"string"
          },
          "value":{
            "type": "integer",
            "minimum": 0,
            "maximum": 100
          }
        }
      }
    }
  }
}
```

initially, that yields, as expected:
```
curl -X GET http://192.168.29.41/test -H 'Content-Type: application/json'
{"x":[]}
```

create entries:
```
curl -X POST http://192.168.29.41/test -H 'Content-Type: application/json' --data '{
                                                         "x": [
                                                           {
                                                             "name": "object 1",
                                                             "value": 1
                                                           },
                                                           {
                                                             "name": "object 2",
                                                             "value": 2
                                                           }
                                                         ]
                                                       }'

```

yields:
```
curl -X GET http://192.168.29.41/test -H 'Content-Type: application/json'
{"x":[{"name":"object 1","value":1},{"name":"object 2","value":2}]}
```
so far, so good.

now if I take the example from the documentation:

```
curl -X POST http://192.168.29.41/test -H 'Content-Type: application/json' --data '{"x[name=object 1]": { "value": 8 }}'
{"error":"FormatError::NotInSchema"}
```

on the console, the output is:
```
received presets bodyStream
[Libraries/ConfigDB/src/Database.cpp:69] [CFGDB] NotInSchema "x[name=object 1]"
[Libraries/ConfigDB/src/Database.cpp:69] [CFGDB] NotInSchema "value"
[Libraries/ConfigDB/src/Json/Format.cpp:77] JSON load 'app-test': FormatError::NotInSchema
```

using numerical indexes in value arrays work fine, but it seems that here might be a problem? 
Or am I gettings something wrong?

**Comment by mikee47** [comment]
It's a bug: fails if the object array is in the root store. PR #64 should fix this.

**Comment by pljakobs** [comment]
ah, great! Testing now!

**Comment by pljakobs** [comment]
and it works! Thank you so much!

**Comment by pljakobs** [comment]
okay, one step back: it works for the simple example, I'm still getting errors for the more complex store.
```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "store":true,
  "properties": {
    "last-color":{
      "$ref":"defs/$defs/hsvct"
    },
    "presets": {
      "type": "array",
      "store":true,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "color": {
            "$ref":"defs/$defs/color"
          },
          "ts": {
            "type": "integer"
          },
          "id":{
            "type":"integer"
          },
          "favorite":{
            "type":"boolean",
            "default":false
          }
        }
      }
    },
    "scenes":{
      "type":"array",
      "store":true,
      "items":{
        "type":"object",
        "properties":{
          "name":{
            "type":"string"
          },
          "settings":{
            "type":"array",
            "items":{
              "type":"object",
              "properties":{
                "controller_id":{
                  "type":"integer"
                },
                "color": {
                  "$ref":"defs/$defs/color"
                }
              }
            }
          }
        }
      }
    }
  }
}

 ```
I'm trying to work with the presets array for now. 
I have pre-populated that from the firmware:
```
curl -X GET http://192.168.29.41/presets -H 'Content-Type: application/json'
{ 
  "last-color":
  {
    "s":100,
    "v":100,
    "h":0,
    "ct":10
  },
  "presets":
  [
    {
      "color":
      {
        "hsv":
        {
          "s":100,
          "v":100
          ,"h":0
        }
      },
      "name":"example-hsv",
      "ts":0,
      "id":0,
      "favorite":true
    },
    {
      "color":
      {
        "raw":
        {
          "ww":255,
          "r":255,
          "b":255,
          "cw":255,
          "g":255
        }
      },
      "name":"example-raw",
      "ts":0,
      "id":0,
      "favorite":false
    }
  ],
"scenes":[...omited...]}
```

If I now try this:
```
curl -X POST http://192.168.29.41/presets -H 'Content-Type: application/json' --data '{"presets[name=example-hsv]":[]}'
```
my expectation would be for example-hsv to be deleted, but the result is
```
{"error":"FormatError::NotInSchema"}
```
```
[Libraries/ConfigDB/src/Database.cpp:69] [CFGDB] NotInSchema "presets[name=example-hsv]" in ""
[Libraries/ConfigDB/src/Json/Format.cpp:77] JSON load 'app-data': FormatError::NotInSchema
[/home/pjakobs/devel/esp_rgbww_firmware/app/webserver.cpp:1282] could not update presets
```

**Comment by pljakobs** [comment]
just noticed that I had both the presets and scenes array defined as stores, that was from the idea where I wanted to use two different endpoints. Testing without that now.

**Comment by mikee47** [comment]
```
{
  "presets[name=example-hsv]": []
}
```

> my expectation would be for example-hsv to be deleted ...

I think you've found another case which ConfigDB doesn't handle. With your initial schema above I tried `{"x[name=object 1]": []}` and it succeeds, but doesn't actually do anything. Re-reading the documentation there is `x: []` to clear the entire array, and whilst there are insert and append mechanisms I don't see anything about deleting array elements (or ranges). So either I didn't documented it or, more likely, that isn't implemented.

**Comment by pljakobs** [comment]
rewrote my code to not use stores but the issue is still present:
```
curl -X GET http://192.168.29.41/presets -H 'Content-Type: application/json'
{"last-color":{"s":100,"v":100,"h":0,"ct":10},"presets":[{"color":{"raw":{"ww":255,"r":255,"b":255,"cw":255,"g":255}},"name":"example-raw","ts":0,"id":0,"favorite":false}],"scenes":[]}
```

trying to set the timestamp of example-raw:
```
curl -X POST http://192.168.29.41/presets -H 'Content-Type: application/json' --data 
'
{
  "presets[name=example-raw]":
  [
    {
      "ts":10
    }
  ]
}
'
```
(I prettified it to verify for myself that the syntax looks ok)
The result:
```
{"error":"FormatError::NotInSchema"}
```
interestingly, the message on the console looks slightly different:
```
[Libraries/ConfigDB/src/Database.cpp:69] [CFGDB] NotInSchema "" in "[0]"
[Libraries/ConfigDB/src/Database.cpp:69] [CFGDB] NotInSchema "ts"
[Libraries/ConfigDB/src/Json/Format.cpp:77] JSON load 'app-data': FormatError::NotInSchema
```
resetting the array with 
```
curl -X POST http://192.168.29.41/presets -H 'Content-Type: application/json' --data '{"presets":[]}'
```
works as expected, though.
so does
```
curl -X POST http://192.168.29.41/presets -H 'Content-Type: application/json' --data '{"presets[]":[{"color":{"hsv":{"h":120,"s":50,"v":75}},"name":"test1","ts":10,"id":1235,"favorite":false}]}'
```

now, with this:
```
curl -X GET http://192.168.29.41/presets -H 'Content-Type: application/json'
{"last-color":{"s":100,"v":100,"h":0,"ct":10},"presets":[{"color":{"hsv":{"s":50,"v":75,"h":60}},"name":"test","ts":10,"id":1234,"favorite":false},{"color":{"hsv":{"s":50,"v":75,"h":120}},"name":"test1","ts":10,"id":1235,"favorite":false}],"scenes":[]}⏎   
```
I would assume that this should remove test1 from the list:
```
curl -X POST http://192.168.29.41/presets -H 'Content-Type: application/json' --data '{"presets[name=test1]":{}}'
{"success":true}
```
but the resulting array has not changed:
```
curl -X GET http://192.168.29.41/presets -H 'Content-Type: application/json'
{"last-color":{"s":100,"v":100,"h":0,"ct":10},"presets":[{"color":{"hsv":{"s":50,"v":75,"h":60}},"name":"test","ts":10,"id":1234,"favorite":false},{"color":{"hsv":{"s":50,"v":75,"h":120}},"name":"test1","ts":10,"id":1235,"favorite":false}],"scenes":[]}
```

**Comment by mikee47** [comment]
```
{
  "presets[name=example-raw]":
  [
    { "ts":10 }
  ]
}
```
should be
```
{
  "presets[name=example-raw]":  {  "ts":10 }
}
```

**Comment by mikee47** [comment]
> So then what doesn't work is deleting items using the selector method?

Correct. It's because a named selector selects exactly one item, but deletion requires a range. Deletion is handled as a side-effect of an insert operation.

**Comment by pljakobs** [comment]
little did I appreciate the complexities of this project when I suggested something like this.

**Comment by mikee47** [comment]
Logically, `x[name=value]` resolves to a single object, so `"x[name=value]": []"` is technically invalid and `"x[name=value]": {}"` is just an empty update. IMHO neither expression can robustly express item deletion.

Deletions such as `"x[0:1]": []` happens when parsing `x[0:1]`, so the content of the right-hand expression isn't yet known.

What might work is if we implement support for an expression like this `"x[name=value:]": []`. So appending the `:` suffix converts a single item into a range. Doesn't have to be `:` of course...

**Comment by mikee47** [comment]
Thinking further about this, I said that `"x[name=value]": []"` is technically invalid, but that's not quite correct since `x` could be an `ObjectArray` of `Array` (or `ObjectArray`).

Also, whilst the *content* of the right-hand expression isn't known we *do* know the element type (object, array, etc.).

So a *possible* simplification is that a named selector is automatically converted to a range where the right-hand side is an array...

**Comment by mikee47** [comment]
> I think in this case, the selector can't be used, or am I wrong? If it's an array of objects containing arrays, you would not assign it an array.

Yes, I think you're right here; they're mutually-exclusive.

> In this way, I think the "x[name=value]":[] wouldn't be overloading another function. But it would be confusing since x[0]:[] means make the array at position 0 empty but not delete it.

Perhaps. But you used the expression above and expected it to delete the entry so on some level it's intuitive!

NB. A side-effect of implementing this change means we can do insertions as well.

**Comment by pljakobs** [comment]
just did a quick check of the new implementation and it seems to work as intended.
I can add, modify and delete array items.

Thank you very much!

**Comment by pljakobs** [comment]
if the selector has multiple hits, still only the first will be processed, right? 
It's easy enough to apply it multiple times until we get an error back, so not a request, just a clarification

**Comment by mikee47** [comment]
Yes, only the first match will be used. This is just for consistency with other named selector operations. It might perhaps be more useful to have this remove *all* matching entries, leaving the insertion position at the last matching item. Would you prefer that?

**Comment by mikee47** [comment]
Could also change update behaviour to modify **all** matching items.

**Comment by mikee47** [comment]
I guess my thinking is that array entries would be unique and accessed via key property, so there should only ever be at most one matching entry. Normally we'd use a regular JSON object but as the schema is fixed that's not possible.

**Comment by pljakobs** [comment]
no, I'm pretty happy with running this through an iteration. But I'm also thinking that my keys should be unique, mostly.

We're probably outside the core use case for the Config part of ConfigDB as I am storing application data, or, probably more correctly, runtime configuration.

If someone was to go even more towards using it as a proper json db (maybe also with some storage that is less write sensitive than the spi flash modules) wanting to change all occurrences of objects that have a specific property might be desireable, but I would, at this point, consider this out of scope.
